### ISSUE TITLE
Diagram

### ISSUE THREAD

**Issue by sauloonze** [zygios/weather_station#1]
Hello,

I am planing to get the 51WS5 module. I am curious to know how did you connect it to the esp32/arduino? 

Thanks

**Comment by zygios** [comment]
Hello,
I get only sensors without meteorological measurement module. All my calculations are done with Arduino and data send to Domitcz server. 
Sensors pinout I took from page https://dwmzone.com/en/usd6-usd10/687-2113-dwm-51ws3-aprs-weather-station-evb-board.html Section B Rainfall sensor interface and C Wind speed and wind direction interface. Additionaly I put BH1750 and BME280 sensors.

**Comment by sauloonze** [comment]
Hi,

That sounds like a good idea. Thanks for your time. I am planning to use ESP32 powered by an Ethernet PoE. I want to use your code to quick start my implementation. 
I still not sure about the pins of the sensor. It doesn't show Vin and GND terminals. I am assuming it doesn't require power or ground. Is that right? Had you just connected the sensor pin on the board? 

Thanks again,

**Comment by zygios** [comment]
Hi,
I used this schematic:
![weahter_station_schematic](https://user-images.githubusercontent.com/36035840/84524309-709ac900-ace2-11ea-913c-5592535e8858.png)

**Comment by sauloonze** [comment]
Thanks very much. I am waiting the sensors to try it.
